"""add timezone field to accounts

Revision ID: 362aa8ee1f06
Revises: a46dfce454b0
Create Date: 2026-04-14 02:06:46.843365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362aa8ee1f06'
down_revision: Union[str, Sequence[str], None] = 'a46dfce454b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'timezone')
    # ### end Alembic commands ###
